/**
 * Recria as leituras diárias com 1 versículo por dia.
 * Usa versículos do Novo Testamento (Evangelhos principalmente) e
 * alguns do Antigo Testamento para variedade.
 * 365 versículos selecionados manualmente para meditação diária.
 */

import mysql from 'mysql2/promise';

const conn = await mysql.createConnection(process.env.DATABASE_URL);

// Limpar leituras diárias existentes
await conn.execute('DELETE FROM daily_readings');
console.log('Leituras diárias removidas.');

// Lista curada de 365 versículos para meditação diária (1 por dia)
// Formato: [bookAbbrev, bookName, chapter, verse, theme]
const dailyVerses = [
  // Janeiro - Mateus (Sermão do Monte)
  ['mt', 'Mateus', 5, 3, 'Bem-aventurados os pobres de espírito'],
  ['mt', 'Mateus', 5, 4, 'Bem-aventurados os que choram'],
  ['mt', 'Mateus', 5, 5, 'Bem-aventurados os mansos'],
  ['mt', 'Mateus', 5, 6, 'Bem-aventurados os que têm fome de justiça'],
  ['mt', 'Mateus', 5, 7, 'Bem-aventurados os misericordiosos'],
  ['mt', 'Mateus', 5, 8, 'Bem-aventurados os puros de coração'],
  ['mt', 'Mateus', 5, 9, 'Bem-aventurados os pacificadores'],
  ['mt', 'Mateus', 5, 10, 'Bem-aventurados os perseguidos por causa da justiça'],
  ['mt', 'Mateus', 5, 13, 'Vós sois o sal da terra'],
  ['mt', 'Mateus', 5, 14, 'Vós sois a luz do mundo'],
  ['mt', 'Mateus', 5, 16, 'Brilhe a vossa luz'],
  ['mt', 'Mateus', 5, 17, 'Não vim revogar, mas cumprir'],
  ['mt', 'Mateus', 5, 20, 'A justiça que excede a dos fariseus'],
  ['mt', 'Mateus', 5, 22, 'Quem se irar contra seu irmão'],
  ['mt', 'Mateus', 5, 23, 'Reconcilia-te com teu irmão'],
  ['mt', 'Mateus', 5, 37, 'Seja o vosso falar: sim, sim; não, não'],
  ['mt', 'Mateus', 5, 39, 'Não resistais ao mal'],
  ['mt', 'Mateus', 5, 40, 'Ao que quiser pleitear contigo'],
  ['mt', 'Mateus', 5, 41, 'Obriga-te a ir uma milha'],
  ['mt', 'Mateus', 5, 42, 'Dá a quem te pede'],
  ['mt', 'Mateus', 5, 44, 'Amai os vossos inimigos'],
  ['mt', 'Mateus', 5, 45, 'Para serdes filhos do vosso Pai'],
  ['mt', 'Mateus', 5, 48, 'Sede perfeitos como vosso Pai celestial'],
  ['mt', 'Mateus', 6, 1, 'Não façais as vossas obras para serdes vistos'],
  ['mt', 'Mateus', 6, 3, 'Que a tua mão esquerda não saiba'],
  ['mt', 'Mateus', 6, 6, 'Entra no teu quarto e ora em secreto'],
  ['mt', 'Mateus', 6, 7, 'Não useis de vãs repetições'],
  ['mt', 'Mateus', 6, 9, 'Pai nosso que estás nos céus'],
  ['mt', 'Mateus', 6, 10, 'Venha o teu reino'],
  ['mt', 'Mateus', 6, 12, 'Perdoa-nos as nossas dívidas'],
  ['mt', 'Mateus', 6, 14, 'Se perdoardes aos homens as suas ofensas'],
  // Fevereiro
  ['mt', 'Mateus', 6, 19, 'Não ajunteis tesouros na terra'],
  ['mt', 'Mateus', 6, 20, 'Ajuntai tesouros no céu'],
  ['mt', 'Mateus', 6, 21, 'Onde estiver o teu tesouro'],
  ['mt', 'Mateus', 6, 22, 'A lâmpada do corpo é o olho'],
  ['mt', 'Mateus', 6, 24, 'Ninguém pode servir a dois senhores'],
  ['mt', 'Mateus', 6, 25, 'Não andeis ansiosos pela vossa vida'],
  ['mt', 'Mateus', 6, 26, 'Olhai as aves do céu'],
  ['mt', 'Mateus', 6, 28, 'Considerai os lírios do campo'],
  ['mt', 'Mateus', 6, 33, 'Buscai primeiro o reino de Deus'],
  ['mt', 'Mateus', 6, 34, 'Não vos preocupeis com o dia de amanhã'],
  ['mt', 'Mateus', 7, 1, 'Não julgueis para não serdes julgados'],
  ['mt', 'Mateus', 7, 3, 'Por que vês o argueiro no olho do teu irmão'],
  ['mt', 'Mateus', 7, 7, 'Pedi e dar-se-vos-á'],
  ['mt', 'Mateus', 7, 9, 'Qual de vós, se o filho lhe pedir pão'],
  ['mt', 'Mateus', 7, 12, 'Tudo o que quereis que os homens vos façam'],
  ['mt', 'Mateus', 7, 13, 'Entrai pela porta estreita'],
  ['mt', 'Mateus', 7, 16, 'Pelos seus frutos os conhecereis'],
  ['mt', 'Mateus', 7, 20, 'Pelos seus frutos os reconhecereis'],
  ['mt', 'Mateus', 7, 21, 'Nem todo o que me diz: Senhor, Senhor'],
  ['mt', 'Mateus', 7, 24, 'Todo aquele que ouve estas palavras e as pratica'],
  ['mt', 'Mateus', 7, 25, 'A chuva caiu e as enchentes vieram'],
  ['mt', 'Mateus', 7, 26, 'Todo aquele que ouve e não pratica'],
  ['mt', 'Mateus', 7, 28, 'Quando Jesus acabou este discurso'],
  ['mt', 'Mateus', 8, 2, 'Senhor, se quiseres, podes tornar-me limpo'],
  ['mt', 'Mateus', 8, 8, 'Senhor, não sou digno de que entres em minha casa'],
  ['mt', 'Mateus', 8, 10, 'Em ninguém achei tamanha fé'],
  ['mt', 'Mateus', 8, 20, 'O Filho do Homem não tem onde reclinar a cabeça'],
  ['mt', 'Mateus', 8, 22, 'Segue-me e deixa os mortos enterrarem os seus mortos'],
  ['mt', 'Mateus', 9, 2, 'Filho, tem ânimo; os teus pecados estão perdoados'],
  ['mt', 'Mateus', 9, 9, 'Segue-me (chamado de Mateus)'],
  // Março - Lucas
  ['lc', 'Lucas', 4, 18, 'O Espírito do Senhor está sobre mim'],
  ['lc', 'Lucas', 6, 20, 'Bem-aventurados vós, os pobres'],
  ['lc', 'Lucas', 6, 27, 'Amai os vossos inimigos'],
  ['lc', 'Lucas', 6, 31, 'Fazei aos outros o que quereis que vos façam'],
  ['lc', 'Lucas', 6, 36, 'Sede misericordiosos como vosso Pai é misericordioso'],
  ['lc', 'Lucas', 6, 37, 'Não julgueis e não sereis julgados'],
  ['lc', 'Lucas', 6, 38, 'Dai e ser-vos-á dado'],
  ['lc', 'Lucas', 6, 43, 'Não há árvore boa que dê mau fruto'],
  ['lc', 'Lucas', 6, 45, 'O homem bom tira do bom tesouro do coração'],
  ['lc', 'Lucas', 6, 46, 'Por que me chamais Senhor, Senhor'],
  ['lc', 'Lucas', 9, 23, 'Se alguém quer vir após mim, negue-se a si mesmo'],
  ['lc', 'Lucas', 9, 24, 'Quem quiser salvar a sua vida, perdê-la-á'],
  ['lc', 'Lucas', 9, 25, 'Que aproveita ao homem ganhar o mundo inteiro'],
  ['lc', 'Lucas', 10, 25, 'Que farei para herdar a vida eterna?'],
  ['lc', 'Lucas', 10, 27, 'Amarás o Senhor teu Deus de todo o coração'],
  ['lc', 'Lucas', 10, 29, 'Quem é o meu próximo?'],
  ['lc', 'Lucas', 10, 33, 'O bom samaritano'],
  ['lc', 'Lucas', 10, 36, 'Qual destes três te parece ter sido próximo?'],
  ['lc', 'Lucas', 10, 37, 'Vai e faze tu o mesmo'],
  ['lc', 'Lucas', 11, 9, 'Pedi e dar-se-vos-á'],
  ['lc', 'Lucas', 11, 13, 'Quanto mais o Pai celestial dará o Espírito Santo'],
  ['lc', 'Lucas', 12, 15, 'Guardai-vos de toda a avareza'],
  ['lc', 'Lucas', 12, 21, 'Assim é o que ajunta tesouros para si'],
  ['lc', 'Lucas', 12, 31, 'Buscai o reino de Deus'],
  ['lc', 'Lucas', 12, 34, 'Onde estiver o vosso tesouro'],
  ['lc', 'Lucas', 12, 48, 'A quem muito foi dado, muito será exigido'],
  ['lc', 'Lucas', 14, 11, 'Todo o que se exaltar será humilhado'],
  ['lc', 'Lucas', 14, 13, 'Quando deres um banquete, convida os pobres'],
  ['lc', 'Lucas', 15, 4, 'A ovelha perdida'],
  ['lc', 'Lucas', 15, 7, 'Mais alegria no céu por um pecador que se arrepende'],
  ['lc', 'Lucas', 15, 11, 'O filho pródigo'],
  // Abril - João
  ['jo', 'João', 1, 1, 'No princípio era o Verbo'],
  ['jo', 'João', 1, 4, 'Nele estava a vida'],
  ['jo', 'João', 1, 5, 'A luz resplandece nas trevas'],
  ['jo', 'João', 1, 9, 'A luz verdadeira que ilumina todo homem'],
  ['jo', 'João', 1, 12, 'A todos os que o receberam'],
  ['jo', 'João', 1, 14, 'O Verbo se fez carne'],
  ['jo', 'João', 3, 3, 'Ninguém pode ver o reino de Deus se não nascer de novo'],
  ['jo', 'João', 3, 5, 'Nascer da água e do Espírito'],
  ['jo', 'João', 3, 6, 'O que é nascido da carne é carne'],
  ['jo', 'João', 3, 7, 'Não te admires de que te disse: Necessário vos é nascer de novo'],
  ['jo', 'João', 3, 16, 'Porque Deus amou o mundo de tal maneira'],
  ['jo', 'João', 3, 17, 'Deus não enviou o seu Filho ao mundo para condenar'],
  ['jo', 'João', 4, 13, 'Quem beber desta água tornará a ter sede'],
  ['jo', 'João', 4, 14, 'A água que eu lhe der será uma fonte de água viva'],
  ['jo', 'João', 4, 23, 'Os verdadeiros adoradores adorarão em espírito e em verdade'],
  ['jo', 'João', 4, 24, 'Deus é Espírito'],
  ['jo', 'João', 5, 17, 'Meu Pai trabalha até agora e eu trabalho também'],
  ['jo', 'João', 5, 24, 'Quem ouve a minha palavra e crê naquele que me enviou'],
  ['jo', 'João', 5, 28, 'Vem a hora em que todos os que estão nos sepulcros ouvirão'],
  ['jo', 'João', 5, 29, 'Os que fizeram o bem ressuscitarão para a vida'],
  ['jo', 'João', 6, 35, 'Eu sou o pão da vida'],
  ['jo', 'João', 6, 40, 'A vontade do meu Pai é que todo aquele que vê o Filho'],
  ['jo', 'João', 6, 44, 'Ninguém pode vir a mim se o Pai não o trouxer'],
  ['jo', 'João', 6, 47, 'Quem crê em mim tem a vida eterna'],
  ['jo', 'João', 6, 63, 'O Espírito é que vivifica; a carne para nada aproveita'],
  ['jo', 'João', 7, 24, 'Não julgueis segundo as aparências'],
  ['jo', 'João', 8, 7, 'Quem de vós está sem pecado, atire primeiro a pedra'],
  ['jo', 'João', 8, 11, 'Vai e não peques mais'],
  ['jo', 'João', 8, 12, 'Eu sou a luz do mundo'],
  ['jo', 'João', 8, 32, 'Conhecereis a verdade e a verdade vos libertará'],
  // Maio - João (continuação)
  ['jo', 'João', 8, 36, 'Se o Filho vos libertar, sereis verdadeiramente livres'],
  ['jo', 'João', 9, 1, 'O cego de nascença'],
  ['jo', 'João', 9, 3, 'Não foi este que pecou, nem seus pais'],
  ['jo', 'João', 9, 4, 'Importa que façamos as obras daquele que me enviou'],
  ['jo', 'João', 10, 7, 'Eu sou a porta das ovelhas'],
  ['jo', 'João', 10, 10, 'Eu vim para que tenham vida e a tenham em abundância'],
  ['jo', 'João', 10, 11, 'Eu sou o bom pastor'],
  ['jo', 'João', 10, 14, 'Eu sou o bom pastor e conheço as minhas ovelhas'],
  ['jo', 'João', 10, 16, 'Tenho outras ovelhas que não são deste aprisco'],
  ['jo', 'João', 10, 27, 'As minhas ovelhas ouvem a minha voz'],
  ['jo', 'João', 10, 30, 'Eu e o Pai somos um'],
  ['jo', 'João', 11, 25, 'Eu sou a ressurreição e a vida'],
  ['jo', 'João', 11, 26, 'Todo o que vive e crê em mim nunca morrerá'],
  ['jo', 'João', 11, 35, 'Jesus chorou'],
  ['jo', 'João', 12, 24, 'Se o grão de trigo não cair na terra e morrer'],
  ['jo', 'João', 12, 25, 'Quem ama a sua vida perdê-la-á'],
  ['jo', 'João', 12, 26, 'Se alguém me serve, siga-me'],
  ['jo', 'João', 12, 32, 'E eu, quando for levantado da terra, todos atrairei a mim'],
  ['jo', 'João', 13, 14, 'Se eu, o Senhor, vos lavei os pés'],
  ['jo', 'João', 13, 15, 'Exemplo vos dei'],
  ['jo', 'João', 13, 34, 'Um novo mandamento vos dou: que vos ameis uns aos outros'],
  ['jo', 'João', 13, 35, 'Nisto conhecerão todos que sois meus discípulos'],
  ['jo', 'João', 14, 1, 'Não se turbe o vosso coração'],
  ['jo', 'João', 14, 2, 'Na casa de meu Pai há muitas moradas'],
  ['jo', 'João', 14, 6, 'Eu sou o caminho, a verdade e a vida'],
  ['jo', 'João', 14, 12, 'Quem crê em mim, as obras que eu faço, ele também as fará'],
  ['jo', 'João', 14, 16, 'Eu rogarei ao Pai e ele vos dará outro Consolador'],
  ['jo', 'João', 14, 17, 'O Espírito da verdade'],
  ['jo', 'João', 14, 23, 'Se alguém me amar, guardará a minha palavra'],
  ['jo', 'João', 14, 27, 'Deixo-vos a paz, a minha paz vos dou'],
  // Junho - João (continuação) e Marcos
  ['jo', 'João', 15, 1, 'Eu sou a videira verdadeira'],
  ['jo', 'João', 15, 4, 'Permanecei em mim e eu em vós'],
  ['jo', 'João', 15, 5, 'Eu sou a videira, vós as varas'],
  ['jo', 'João', 15, 7, 'Se permanecerdes em mim e as minhas palavras permanecerem'],
  ['jo', 'João', 15, 9, 'Assim como o Pai me amou, também eu vos amei'],
  ['jo', 'João', 15, 12, 'Este é o meu mandamento: que vos ameis uns aos outros'],
  ['jo', 'João', 15, 13, 'Ninguém tem maior amor do que este'],
  ['jo', 'João', 15, 16, 'Não me escolhestes vós a mim, mas eu vos escolhi a vós'],
  ['jo', 'João', 16, 7, 'Convém-vos que eu vá; se eu não for, o Consolador não virá'],
  ['jo', 'João', 16, 13, 'Quando vier o Espírito da verdade, ele vos guiará'],
  ['jo', 'João', 16, 22, 'Também vós agora tendes tristeza; mas tornarei a ver-vos'],
  ['jo', 'João', 16, 33, 'No mundo passais por aflições; mas tende bom ânimo'],
  ['jo', 'João', 17, 3, 'Esta é a vida eterna: que te conheçam a ti, o único Deus verdadeiro'],
  ['jo', 'João', 17, 11, 'Pai santo, guarda-os no teu nome'],
  ['jo', 'João', 17, 21, 'Para que todos sejam um'],
  ['jo', 'João', 20, 21, 'Assim como o Pai me enviou, também eu vos envio'],
  ['jo', 'João', 20, 22, 'Recebei o Espírito Santo'],
  ['mc', 'Marcos', 1, 15, 'O reino de Deus está próximo; arrependei-vos'],
  ['mc', 'Marcos', 1, 17, 'Vinde após mim e eu farei que sejais pescadores de homens'],
  ['mc', 'Marcos', 2, 17, 'Não vim chamar os justos, mas os pecadores'],
  ['mc', 'Marcos', 2, 27, 'O sábado foi feito por causa do homem'],
  ['mc', 'Marcos', 4, 3, 'O semeador saiu a semear'],
  ['mc', 'Marcos', 4, 20, 'Os que foram semeados em boa terra'],
  ['mc', 'Marcos', 4, 22, 'Não há nada oculto que não haja de ser manifesto'],
  ['mc', 'Marcos', 4, 24, 'Atendei ao que ouvis'],
  ['mc', 'Marcos', 4, 26, 'O reino de Deus é como um homem que lança semente'],
  ['mc', 'Marcos', 4, 30, 'A que compararemos o reino de Deus?'],
  ['mc', 'Marcos', 6, 4, 'O profeta não é desprezado senão na sua pátria'],
  ['mc', 'Marcos', 8, 34, 'Se alguém quer vir após mim, negue-se a si mesmo'],
  ['mc', 'Marcos', 8, 36, 'Que aproveitará ao homem ganhar o mundo inteiro'],
  ['mc', 'Marcos', 9, 35, 'Se alguém quiser ser o primeiro, será o último de todos'],
  ['mc', 'Marcos', 10, 14, 'Deixai as crianças virem a mim'],
  ['mc', 'Marcos', 10, 15, 'Quem não receber o reino de Deus como uma criança'],
  ['mc', 'Marcos', 10, 21, 'Uma coisa te falta: vai, vende tudo o que tens'],
  ['mc', 'Marcos', 10, 43, 'Qualquer que entre vós quiser ser grande'],
  ['mc', 'Marcos', 10, 45, 'O Filho do Homem não veio para ser servido'],
  ['mc', 'Marcos', 12, 29, 'O primeiro de todos os mandamentos'],
  ['mc', 'Marcos', 12, 30, 'Amarás o Senhor teu Deus de todo o teu coração'],
  ['mc', 'Marcos', 12, 31, 'Amarás o teu próximo como a ti mesmo'],
  ['mc', 'Marcos', 12, 33, 'Amar a Deus e ao próximo vale mais que holocaustos'],
  // Julho - Antigo Testamento (Salmos)
  ['sl', 'Salmos', 1, 1, 'Bem-aventurado o homem que não anda no conselho dos ímpios'],
  ['sl', 'Salmos', 1, 2, 'Antes tem o seu prazer na lei do Senhor'],
  ['sl', 'Salmos', 1, 3, 'Será como árvore plantada junto a ribeiros de águas'],
  ['sl', 'Salmos', 8, 4, 'Que é o homem para que te lembres dele?'],
  ['sl', 'Salmos', 16, 8, 'Tenho sempre o Senhor diante de mim'],
  ['sl', 'Salmos', 19, 1, 'Os céus proclamam a glória de Deus'],
  ['sl', 'Salmos', 22, 1, 'Deus meu, Deus meu, por que me abandonaste?'],
  ['sl', 'Salmos', 23, 1, 'O Senhor é o meu pastor'],
  ['sl', 'Salmos', 23, 2, 'Em verdes prados me faz repousar'],
  ['sl', 'Salmos', 23, 4, 'Ainda que eu andasse pelo vale da sombra da morte'],
  ['sl', 'Salmos', 23, 6, 'A bondade e a misericórdia me seguirão todos os dias'],
  ['sl', 'Salmos', 24, 1, 'Do Senhor é a terra e a sua plenitude'],
  ['sl', 'Salmos', 25, 4, 'Faze-me conhecer os teus caminhos, Senhor'],
  ['sl', 'Salmos', 27, 1, 'O Senhor é a minha luz e a minha salvação'],
  ['sl', 'Salmos', 27, 4, 'Uma coisa pedi ao Senhor'],
  ['sl', 'Salmos', 30, 5, 'O choro pode durar uma noite, mas a alegria vem pela manhã'],
  ['sl', 'Salmos', 31, 15, 'Os meus tempos estão nas tuas mãos'],
  ['sl', 'Salmos', 32, 1, 'Bem-aventurado aquele cuja transgressão é perdoada'],
  ['sl', 'Salmos', 34, 8, 'Provai e vede que o Senhor é bom'],
  ['sl', 'Salmos', 34, 18, 'O Senhor está perto dos que têm o coração quebrantado'],
  ['sl', 'Salmos', 37, 4, 'Deleita-te no Senhor e ele te concederá o que deseja o teu coração'],
  ['sl', 'Salmos', 37, 7, 'Descansa no Senhor e espera por ele'],
  ['sl', 'Salmos', 40, 1, 'Esperando, esperei no Senhor'],
  ['sl', 'Salmos', 42, 1, 'Como o cervo brama pelas correntes das águas'],
  ['sl', 'Salmos', 46, 1, 'Deus é o nosso refúgio e força'],
  ['sl', 'Salmos', 46, 10, 'Aquietai-vos e sabei que eu sou Deus'],
  ['sl', 'Salmos', 51, 1, 'Tem misericórdia de mim, ó Deus'],
  ['sl', 'Salmos', 51, 10, 'Cria em mim, ó Deus, um coração puro'],
  ['sl', 'Salmos', 51, 17, 'Os sacrifícios de Deus são o espírito quebrantado'],
  ['sl', 'Salmos', 62, 1, 'Só em Deus repousa a minha alma'],
  ['sl', 'Salmos', 63, 1, 'Ó Deus, tu és o meu Deus; de madrugada te busco'],
  // Agosto - Provérbios e Eclesiastes
  ['pv', 'Provérbios', 1, 7, 'O temor do Senhor é o princípio da sabedoria'],
  ['pv', 'Provérbios', 3, 5, 'Confia no Senhor de todo o teu coração'],
  ['pv', 'Provérbios', 3, 6, 'Em todos os teus caminhos, reconhece-o'],
  ['pv', 'Provérbios', 3, 7, 'Não sejas sábio aos teus próprios olhos'],
  ['pv', 'Provérbios', 4, 7, 'O principal é a sabedoria'],
  ['pv', 'Provérbios', 4, 18, 'A vereda dos justos é como a luz da aurora'],
  ['pv', 'Provérbios', 8, 17, 'Eu amo os que me amam'],
  ['pv', 'Provérbios', 10, 12, 'O ódio desperta contendas, mas o amor cobre todas as faltas'],
  ['pv', 'Provérbios', 11, 2, 'Com a soberba vem a desonra; com os humildes está a sabedoria'],
  ['pv', 'Provérbios', 11, 24, 'Há quem dê liberalmente e ainda aumenta'],
  ['pv', 'Provérbios', 12, 17, 'O que fala a verdade declara o que é justo'],
  ['pv', 'Provérbios', 13, 12, 'A esperança que se prolonga adoece o coração'],
  ['pv', 'Provérbios', 14, 12, 'Há um caminho que parece direito ao homem'],
  ['pv', 'Provérbios', 15, 1, 'A resposta branda desvia o furor'],
  ['pv', 'Provérbios', 16, 18, 'A soberba precede a destruição'],
  ['pv', 'Provérbios', 16, 32, 'Melhor é o sofredor de espírito do que o guerreiro forte'],
  ['pv', 'Provérbios', 17, 17, 'O amigo ama em todo o tempo'],
  ['pv', 'Provérbios', 17, 22, 'O coração alegre é um bom remédio'],
  ['pv', 'Provérbios', 18, 21, 'A morte e a vida estão no poder da língua'],
  ['pv', 'Provérbios', 19, 17, 'Quem tem misericórdia do pobre empresta ao Senhor'],
  ['pv', 'Provérbios', 20, 22, 'Não digas: Vingarei o mal; espera no Senhor'],
  ['pv', 'Provérbios', 21, 2, 'Todo caminho do homem é reto aos seus próprios olhos'],
  ['pv', 'Provérbios', 22, 6, 'Ensina a criança no caminho em que deve andar'],
  ['pv', 'Provérbios', 24, 16, 'Porque o justo cai sete vezes e se levanta'],
  ['pv', 'Provérbios', 25, 21, 'Se o teu inimigo tiver fome, dá-lhe pão'],
  ['pv', 'Provérbios', 27, 1, 'Não te glories do dia de amanhã'],
  ['ec', 'Eclesiastes', 1, 2, 'Vaidade das vaidades, diz o pregador'],
  ['ec', 'Eclesiastes', 3, 1, 'Tudo tem o seu tempo determinado'],
  ['ec', 'Eclesiastes', 3, 11, 'Tudo fez formoso no seu tempo; também pôs a eternidade no coração'],
  ['ec', 'Eclesiastes', 5, 2, 'Não te precipites com a tua boca'],
  ['ec', 'Eclesiastes', 7, 8, 'Melhor é o fim de uma coisa do que o seu começo'],
  // Setembro - Isaías e Jeremias
  ['is', 'Isaías', 1, 18, 'Vinde, e arrazoemos, diz o Senhor'],
  ['is', 'Isaías', 6, 8, 'Aqui estou eu, envia-me a mim'],
  ['is', 'Isaías', 9, 6, 'Porque um menino nos nasceu, um filho nos foi dado'],
  ['is', 'Isaías', 11, 6, 'O lobo habitará com o cordeiro'],
  ['is', 'Isaías', 25, 8, 'Tragará a morte para sempre'],
  ['is', 'Isaías', 26, 3, 'Tu conservarás em perfeita paz aquele cujo pensamento está firme em ti'],
  ['is', 'Isaías', 40, 1, 'Consolai, consolai o meu povo'],
  ['is', 'Isaías', 40, 28, 'Não sabes tu? Não ouviste que o Deus eterno é o Senhor?'],
  ['is', 'Isaías', 40, 29, 'Ele dá força ao cansado'],
  ['is', 'Isaías', 40, 31, 'Os que esperam no Senhor renovam as suas forças'],
  ['is', 'Isaías', 41, 10, 'Não temas, porque eu sou contigo'],
  ['is', 'Isaías', 43, 1, 'Não temas, porque eu te remi'],
  ['is', 'Isaías', 43, 2, 'Quando passares pelas águas, eu serei contigo'],
  ['is', 'Isaías', 43, 19, 'Eis que faço uma coisa nova'],
  ['is', 'Isaías', 49, 15, 'Pode uma mulher esquecer-se do filho que ainda mama?'],
  ['is', 'Isaías', 53, 3, 'Era desprezado e rejeitado pelos homens'],
  ['is', 'Isaías', 53, 4, 'Verdadeiramente ele tomou sobre si as nossas enfermidades'],
  ['is', 'Isaías', 53, 5, 'Mas ele foi ferido pelas nossas transgressões'],
  ['is', 'Isaías', 55, 1, 'Ó todos os que tendes sede, vinde às águas'],
  ['is', 'Isaías', 55, 6, 'Buscai ao Senhor enquanto se pode achar'],
  ['is', 'Isaías', 55, 8, 'Os meus pensamentos não são os vossos pensamentos'],
  ['is', 'Isaías', 55, 11, 'A minha palavra não voltará para mim vazia'],
  ['is', 'Isaías', 58, 6, 'Não é este o jejum que escolhi?'],
  ['is', 'Isaías', 58, 7, 'Não é repartir o teu pão com o faminto?'],
  ['is', 'Isaías', 61, 1, 'O Espírito do Senhor está sobre mim'],
  ['jr', 'Jeremias', 17, 7, 'Bendito o homem que confia no Senhor'],
  ['jr', 'Jeremias', 17, 9, 'Enganoso é o coração, mais do que todas as coisas'],
  ['jr', 'Jeremias', 29, 11, 'Porque eu sei os pensamentos que tenho a vosso respeito'],
  ['jr', 'Jeremias', 29, 13, 'Buscar-me-eis e me achareis quando me buscardes de todo o vosso coração'],
  ['jr', 'Jeremias', 31, 3, 'Com amor eterno te amei'],
  // Outubro - Epístolas de Paulo
  ['rm', 'Romanos', 1, 20, 'As perfeições invisíveis de Deus são claramente vistas'],
  ['rm', 'Romanos', 2, 6, 'Deus retribuirá a cada um segundo as suas obras'],
  ['rm', 'Romanos', 5, 3, 'Gloriamo-nos também nas tribulações'],
  ['rm', 'Romanos', 5, 5, 'O amor de Deus está derramado em nossos corações'],
  ['rm', 'Romanos', 6, 23, 'O salário do pecado é a morte'],
  ['rm', 'Romanos', 8, 6, 'O pendor da carne é morte; mas o pendor do Espírito é vida e paz'],
  ['rm', 'Romanos', 8, 14, 'Todos os que são guiados pelo Espírito de Deus são filhos de Deus'],
  ['rm', 'Romanos', 8, 18, 'Os sofrimentos do tempo presente não são comparáveis'],
  ['rm', 'Romanos', 8, 28, 'Sabemos que todas as coisas contribuem para o bem daqueles que amam a Deus'],
  ['rm', 'Romanos', 8, 38, 'Estou persuadido de que nem a morte, nem a vida nos poderá separar do amor de Deus'],
  ['rm', 'Romanos', 12, 2, 'Não vos conformeis com este século'],
  ['rm', 'Romanos', 12, 9, 'O amor seja sem fingimento'],
  ['rm', 'Romanos', 12, 12, 'Alegrai-vos na esperança, sede pacientes na tribulação'],
  ['rm', 'Romanos', 12, 14, 'Abençoai os que vos perseguem'],
  ['rm', 'Romanos', 12, 17, 'A ninguém pagueis mal por mal'],
  ['rm', 'Romanos', 12, 18, 'Se possível, quanto depender de vós, tende paz com todos os homens'],
  ['rm', 'Romanos', 12, 19, 'A mim pertence a vingança; eu recompensarei, diz o Senhor'],
  ['rm', 'Romanos', 12, 20, 'Se o teu inimigo tiver fome, dá-lhe de comer'],
  ['rm', 'Romanos', 12, 21, 'Não sejas vencido do mal, mas vence o mal com o bem'],
  ['rm', 'Romanos', 13, 8, 'A ninguém deveis coisa alguma, senão o amor mútuo'],
  ['rm', 'Romanos', 13, 10, 'O amor não faz mal ao próximo'],
  ['rm', 'Romanos', 14, 6, 'Aquele que faz caso do dia, para o Senhor o faz'],
  ['rm', 'Romanos', 14, 12, 'Cada um de nós dará conta de si mesmo a Deus'],
  ['rm', 'Romanos', 15, 1, 'Devemos nós, os fortes, suportar as fraquezas dos fracos'],
  ['co1', '1 Coríntios', 2, 9, 'Olho não viu, nem ouvido ouviu'],
  ['co1', '1 Coríntios', 3, 16, 'Não sabeis que sois o templo de Deus?'],
  ['co1', '1 Coríntios', 6, 19, 'O vosso corpo é o templo do Espírito Santo'],
  ['co1', '1 Coríntios', 10, 13, 'Não vos sobreveio tentação que não fosse humana'],
  ['co1', '1 Coríntios', 12, 4, 'Há diversidade de dons, mas o Espírito é o mesmo'],
  ['co1', '1 Coríntios', 12, 26, 'Se um membro sofre, todos os membros sofrem com ele'],
  // Novembro - 1 Coríntios 13 e outras epístolas
  ['co1', '1 Coríntios', 13, 1, 'Ainda que eu fale as línguas dos homens e dos anjos'],
  ['co1', '1 Coríntios', 13, 2, 'Ainda que eu tivesse o dom de profecia'],
  ['co1', '1 Coríntios', 13, 3, 'Ainda que eu distribuísse todos os meus bens'],
  ['co1', '1 Coríntios', 13, 4, 'O amor é sofredor e benigno'],
  ['co1', '1 Coríntios', 13, 5, 'O amor não se porta inconvenientemente'],
  ['co1', '1 Coríntios', 13, 6, 'O amor não se alegra com a injustiça'],
  ['co1', '1 Coríntios', 13, 7, 'O amor tudo sofre, tudo crê, tudo espera, tudo suporta'],
  ['co1', '1 Coríntios', 13, 8, 'O amor nunca falha'],
  ['co1', '1 Coríntios', 13, 12, 'Agora vemos por espelho em enigma'],
  ['co1', '1 Coríntios', 13, 13, 'Agora, pois, permanecem a fé, a esperança e o amor'],
  ['co1', '1 Coríntios', 15, 22, 'Porque, assim como em Adão todos morrem'],
  ['co1', '1 Coríntios', 15, 42, 'Assim também é a ressurreição dos mortos'],
  ['co1', '1 Coríntios', 15, 44, 'Semeia-se corpo animal, ressuscita corpo espiritual'],
  ['co1', '1 Coríntios', 15, 52, 'Num momento, num abrir e fechar de olhos'],
  ['gl', 'Gálatas', 5, 14, 'Toda a lei se cumpre numa só palavra: Amarás o teu próximo'],
  ['gl', 'Gálatas', 5, 22, 'O fruto do Espírito é: amor, alegria, paz'],
  ['gl', 'Gálatas', 6, 2, 'Levai os fardos uns dos outros'],
  ['gl', 'Gálatas', 6, 7, 'Não vos enganeis: Deus não se deixa zombar'],
  ['gl', 'Gálatas', 6, 9, 'Não nos cansemos de fazer o bem'],
  ['ef', 'Efésios', 2, 8, 'Pela graça sois salvos, mediante a fé'],
  ['ef', 'Efésios', 4, 1, 'Rogo-vos que andeis de modo digno da vocação com que fostes chamados'],
  ['ef', 'Efésios', 4, 2, 'Com toda a humildade e mansidão'],
  ['ef', 'Efésios', 4, 26, 'Não se ponha o sol sobre a vossa ira'],
  ['ef', 'Efésios', 4, 32, 'Sede bondosos e misericordiosos uns para com os outros'],
  ['ef', 'Efésios', 5, 1, 'Sede, pois, imitadores de Deus'],
  ['ef', 'Efésios', 6, 10, 'Fortalecei-vos no Senhor e na força do seu poder'],
  ['fp', 'Filipenses', 2, 3, 'Nada façais por contenda ou por vanglória'],
  ['fp', 'Filipenses', 2, 4, 'Não atendendo cada um ao que é seu'],
  ['fp', 'Filipenses', 2, 5, 'Tende em vós o mesmo sentimento que houve em Cristo Jesus'],
  ['fp', 'Filipenses', 4, 4, 'Regozijai-vos no Senhor sempre'],
  ['fp', 'Filipenses', 4, 6, 'Não andeis ansiosos por coisa alguma'],
  ['fp', 'Filipenses', 4, 7, 'A paz de Deus, que excede todo o entendimento'],
  ['fp', 'Filipenses', 4, 8, 'Tudo o que é verdadeiro, tudo o que é honesto'],
  ['fp', 'Filipenses', 4, 11, 'Aprendi a estar contente em qualquer estado em que me encontre'],
  ['fp', 'Filipenses', 4, 13, 'Posso tudo naquele que me fortalece'],
  // Dezembro - Epístolas gerais e Apocalipse
  ['tg', 'Tiago', 1, 2, 'Meus irmãos, tende grande alegria quando cairdes em várias tentações'],
  ['tg', 'Tiago', 1, 5, 'Se algum de vós tem falta de sabedoria, peça-a a Deus'],
  ['tg', 'Tiago', 1, 17, 'Toda a boa dádiva e todo o dom perfeito vêm do alto'],
  ['tg', 'Tiago', 1, 22, 'Sede cumpridores da palavra e não somente ouvintes'],
  ['tg', 'Tiago', 2, 14, 'De que aproveita, meus irmãos, se alguém disser que tem fé'],
  ['tg', 'Tiago', 2, 17, 'Assim também a fé, se não tiver obras, é morta em si mesma'],
  ['tg', 'Tiago', 2, 26, 'Assim como o corpo sem o espírito é morto'],
  ['tg', 'Tiago', 3, 2, 'Todos tropeçamos em muitas coisas'],
  ['tg', 'Tiago', 3, 17, 'A sabedoria que vem do alto é, primeiro, pura'],
  ['tg', 'Tiago', 4, 6, 'Deus resiste aos soberbos, mas dá graça aos humildes'],
  ['tg', 'Tiago', 4, 7, 'Sujeitai-vos, pois, a Deus; resisti ao diabo'],
  ['tg', 'Tiago', 4, 10, 'Humilhai-vos perante o Senhor e ele vos exaltará'],
  ['tg', 'Tiago', 5, 16, 'Confessai as vossas culpas uns aos outros'],
  ['pe1', '1 Pedro', 1, 7, 'A prova da vossa fé, muito mais preciosa do que o ouro'],
  ['pe1', '1 Pedro', 2, 21, 'Para isso fostes chamados, porque também Cristo sofreu'],
  ['pe1', '1 Pedro', 3, 9, 'Não pagueis mal por mal, nem injúria por injúria'],
  ['pe1', '1 Pedro', 4, 8, 'Antes de tudo, tende ardente amor uns para com os outros'],
  ['pe1', '1 Pedro', 5, 6, 'Humilhai-vos, pois, sob a poderosa mão de Deus'],
  ['pe1', '1 Pedro', 5, 7, 'Lançando sobre ele toda a vossa ansiedade'],
  ['jo1', '1 João', 1, 7, 'Se andarmos na luz, como ele está na luz'],
  ['jo1', '1 João', 2, 6, 'Quem diz que permanece nele deve andar como ele andou'],
  ['jo1', '1 João', 3, 1, 'Vede que grande amor nos tem dado o Pai'],
  ['jo1', '1 João', 3, 14, 'Nós sabemos que já passamos da morte para a vida'],
  ['jo1', '1 João', 3, 18, 'Filhinhos, não amemos de palavra, nem de língua'],
  ['jo1', '1 João', 4, 7, 'Amados, amemo-nos uns aos outros'],
  ['jo1', '1 João', 4, 8, 'Quem não ama não conhece a Deus, porque Deus é amor'],
  ['jo1', '1 João', 4, 11, 'Amados, se Deus assim nos amou, devemos nós também amar-nos uns aos outros'],
  ['jo1', '1 João', 4, 16, 'Deus é amor; e quem permanece no amor permanece em Deus'],
  ['jo1', '1 João', 4, 18, 'No amor não há temor; antes o perfeito amor lança fora o temor'],
  ['jo1', '1 João', 4, 20, 'Se alguém diz: Amo a Deus, e aborrece a seu irmão'],
  ['jo1', '1 João', 4, 21, 'Quem ama a Deus ame também a seu irmão'],
  ['ap', 'Apocalipse', 2, 4, 'Tenho, porém, contra ti que abandonaste o teu primeiro amor'],
  ['ap', 'Apocalipse', 2, 10, 'Sê fiel até à morte e dar-te-ei a coroa da vida'],
  ['ap', 'Apocalipse', 3, 8, 'Eis que pus diante de ti uma porta aberta'],
  ['ap', 'Apocalipse', 3, 20, 'Eis que estou à porta e bato'],
  ['ap', 'Apocalipse', 21, 1, 'Vi um novo céu e uma nova terra'],
  ['ap', 'Apocalipse', 21, 3, 'Eis o tabernáculo de Deus com os homens'],
  ['ap', 'Apocalipse', 21, 4, 'E Deus limpará de seus olhos toda a lágrima'],
  ['ap', 'Apocalipse', 21, 5, 'Eis que faço novas todas as coisas'],
  ['ap', 'Apocalipse', 22, 12, 'Eis que venho sem demora e o meu galardão está comigo'],
  ['ap', 'Apocalipse', 22, 13, 'Eu sou o Alfa e o Ômega'],
  ['ap', 'Apocalipse', 22, 17, 'O Espírito e a esposa dizem: Vem!'],
  ['ap', 'Apocalipse', 22, 20, 'Certamente venho sem demora. Amém! Vem, Senhor Jesus!'],
];

// Gerar datas para 365 dias a partir de hoje
const today = new Date('2026-01-01');
const values = [];

for (let i = 0; i < Math.min(365, dailyVerses.length); i++) {
  const date = new Date(today);
  date.setDate(today.getDate() + i);
  const dateStr = date.toISOString().split('T')[0];
  const [bookAbbrev, bookName, chapter, verse, theme] = dailyVerses[i];
  
  values.push([dateStr, bookAbbrev, bookName, chapter, verse, verse, theme]);
}

// Inserir em lotes
const batchSize = 50;
for (let i = 0; i < values.length; i += batchSize) {
  const batch = values.slice(i, i + batchSize);
  const placeholders = batch.map(() => '(?, ?, ?, ?, ?, ?, ?)').join(', ');
  const flatValues = batch.flat();
  await conn.execute(
    `INSERT INTO daily_readings (date, bookAbbrev, bookName, chapter, verseStart, verseEnd, theme) VALUES ${placeholders}`,
    flatValues
  );
  console.log(`Inseridos ${Math.min(i + batchSize, values.length)} de ${values.length}`);
}

console.log(`\n✅ ${values.length} leituras diárias criadas (1 versículo por dia).`);
await conn.end();
